Support pwsh format for show-env export
taiki-e/cargo-llvm-cov pull request #411
Opened 2024-12-30 00:45 UTC by LittleBoxOfSunshine

This PR demonstrates a solution for #395, with a slightly different strategy that what was discussed. 

The issues outlined there:
1. No pre-built in option for ouputing PowerShell syntax
2. PowerShell has very different (and frankly fairly obtuse) escaping rules which is an impediment for 1. Specifically, env vars like `CARGO_ENCODED_RUSTFLAGS` take non-printable characters that unix shells will accept but pwsh won't.

Additionally, the shell escape crate used is escaping [for cmd](https://docs.rs/shell-escape/0.1.5/shell_escape/windows/index.html), not pwsh and wouldn't be compatible.

Pwsh does accept embedded unicode codes in strings though. If we encode the values this way, we don't need to worry about printable vs non-printable characters nor any of the specifics for what kinds of characters need to be escaped for what kinds of strings. This is a one-time, very fast operation. Once the emitted string is executed all the escapes are gone.

This approach wouldn't be good for a general-purpose escape function, but it's perfectly suitable for this use case.

The change enables users to execute a pwsh version of the source demo:

> Invoke-Expression (cargo llvm-cov show-env --export-pwsh-prefix | Out-String)

Primary goal was to confirm this approach worked. If this is of interest, I can make any changes to the code organization, arg name, etc. The current organization is just what came to mind as I played around with the repo.

Manual test context with binary data in env:

![Pasted image 20241229144731](https://github.com/user-attachments/assets/e455b115-22a2-496d-9109-fbe28662e47a)

Intermediate state example:

![Pasted image 20241229145125](https://github.com/user-attachments/assets/563f869b-e88e-48f6-9dae-1306bfa33464)

Final result:
![Pasted image 20241229145255](https://github.com/user-attachments/assets/631cd693-c816-477a-b895-337e6d83e973)

2024-12-30 00:54 UTC, LittleBoxOfSunshine commented on src/cli.rs
> +    /// Each value: "$env:{key}=@'\n{}\n", escaped using [`shell_escape::escape`].
Stale comment needs to be fixed

2025-01-03 20:03 UTC, asvrada commented on docs/cargo-llvm-cov-show-env.txt
> +            to be used with Invoke-Expression in pwsh.
`in pwsh` to `in PowerShell`

2025-01-05 03:04 UTC, asvrada commented
Thanks for this! Confirmed doesn't work with PowerShell Version 5.1. Other than that, it looks good.

2025-01-05 03:05 UTC, asvrada approved these changes

2025-01-09 12:58 UTC, taiki-e requested changes
Thanks!

2025-01-09 12:58 UTC, taiki-e commented on docs/cargo-llvm-cov-show-env.txt
> +        --export-pwsh-prefix
"--export-prefix" is a name from it emits env vars with "export " prefix. ("export" here is a noun, not a verb)

So, naming something like "--pwsh-env-prefix" (or "--with-pwsh-env-prefix" discussed in https://github.com/taiki-e/cargo-llvm-cov/issues/320#issuecomment-1816773684) is better here.

2025-01-09 18:18 UTC, LittleBoxOfSunshine commented on docs/cargo-llvm-cov-show-env.txt
> +            to be used with Invoke-Expression in pwsh.
Since it requires the newer edition, I'm inclined to stick with `pwsh`. That's the common disambiugation for this needs powershell core vs windows powershell. E.g. you launch with `pwsh` and in ado pipelines it's `pwsh` is always powershell core whereas the `powershell` task is powershell core on mac + linux but windows powershell on windows. Does that change your thinking?

2025-01-09 18:19 UTC, LittleBoxOfSunshine commented on docs/cargo-llvm-cov-show-env.txt
> +            to be used with Invoke-Expression in pwsh.
Oh I'm sorry I misread that. This is the doc part. Agreed, I'll explicitly call that out

2025-01-10 14:18 UTC, taiki-e approved these changes

2025-01-10 14:19 UTC, merged

2025-01-16 16:43 UTC, taiki-e commented
Published in 0.6.16.